### ISSUE TITLE
Case insensitive OS

### ISSUE THREAD

**Issue by ruslo** [scumm/foobar#1]
There are two files: foobar.hpp and FooBar.hpp. On case-insensitive OS like Windows this will not work. I've got next error on Cygwin (i.e. Windows):
```bash
> ./cmake.sh build
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++.exe
-- Check for working CXX compiler: /usr/bin/c++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
## Build Type: MONOLITHIC
-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE)
## Build Type: MONOLITHIC
-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE)
-- Configuring done
-- Generating done
-- Build files have been written to: /.../foobar/build
Scanning dependencies of target foobar_lib
[ 50%] Building CXX object foobar-lib/CMakeFiles/foobar_lib.dir/src/FooBar.cpp.o
Linking CXX shared library cygfoobar_lib.dll
[ 50%] Built target foobar_lib
Scanning dependencies of target foobar_bin
[100%] Building CXX object foobar-bin/CMakeFiles/foobar_bin.dir/src/main.cpp.o
/.../test/foobar/foobar-bin/src/main.cpp: In function ‘int main(int, char**)’:
/.../test/foobar/foobar-bin/src/main.cpp:8:2: error: ‘FooBar’ was not declared in this scope
  FooBar fooBar;
  ^
/.../test/foobar/foobar-bin/src/main.cpp:9:2: error: ‘fooBar’ was not declared in this scope
  fooBar.say();
  ^
foobar-bin/CMakeFiles/foobar_bin.dir/build.make:54: recipe for target 'foobar-bin/CMakeFiles/foobar_bin.dir/src/main.cpp.o' failed
make[2]: *** [foobar-bin/CMakeFiles/foobar_bin.dir/src/main.cpp.o] Error 1
CMakeFiles/Makefile2:125: recipe for target 'foobar-bin/CMakeFiles/foobar_bin.dir/all' failed
make[1]: *** [foobar-bin/CMakeFiles/foobar_bin.dir/all] Error 2
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2
```

Note that there is no 'FooBar.hpp not found' error. This is because 'foobar.hpp' included instead

**Comment by scumm** [comment]
Hi ruslo, you are right! I created the project on linux, so I didn't notice that. I think I should remove the unnecessary PkgConfig as well. Now regarding the structure, I tried to bring some of the characteristics that I like from the the excellent Java Maven tool. Notably:

1) One produced artifact per module. That makes the configuration simpler. It could be further simplified if I also removed the generation of the pkgconfig metadata (however I find that better than cmake's own generated metadata).

2) The project should be build-able either monolithically (all in one go), or per module. This is a great characteristic of Maven that I don't see in a lot of CMake projects. In order to do that, the following are needed:

A) An aggregator script (root CMakeLists.txt).
B) An inheritance script (for common configuration, I used CMakeInclude.txt).
C) Each module to install its artifact and metadata to the "OS repository", e.g. on Linux is /usr/local/...
D) Each module to not assume the existence of the other modules, but check if they are missing and find them as dependencies.

I hope you found some of these useful.

Cheers

**Comment by ruslo** [comment]
> pkgconfig metadata (however I find that better than cmake's own generated metadata)

Note that pkgconfig is unix specific as far as I know. What kind of metadata CMake doens't have?

> This is a great characteristic of Maven that I don't see in a lot of CMake projects

You can divide your project into core, examples, samples, subdirectories. Each of it can be part of main project (add_subdirectory) or as a stand-alone project (find_package). What is the problem?
